---
title: "Week 05 Homework"
author: "Brian Ritz"
date: "Monday, May 18, 2015"
output: html_document
---


Load data from TSA package (the package is written by textbook authors Jonathan Cryer and Kung-Sik Chan).

>library("TSA")

>data(beersales)

The data is the monthly beer sales in millions of barrels, 01/1975 - 12/1990.

Part 1 - use ARIMA(p,d,q) model to forecast beer sales for all months of 1990.

1A - Use the h-period in forecast() to forecast each month of 1990.

1B - Use the monthly data as a continuous time series. Forecast for 1990 Jan, Plug forecast into the time series to forecast for 1990 Feb. And so on and so forth.

1C - which of the two above approaches yield the better results in terms of Mean Squared Error 1990?

Part 2 - use month of the year seasonal ARIMA(p,d,q)(P,Q,D)s model to forecast beer sales for all the months of 1990.

Part 3 - Which model (Part 1 or Part 2) is better to forecast beer sales for each month of 1990 (Jan, Feb, ..., Dec) ? 

Due date: 2015 Feb 19th 11:59pm

```{r}
# load the dataset

library("TSA")
data(beersales)
```

